id: P010633
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG5479
  title: མངོན་རྟོགས་རྒྱན་འགྲེལ་དང་དབུ་མའི་རྟེན་འབྲེལ་སྟོད་པ་སོགས་
  author: ''
  volumes:
    bc3cf7b3f23543b1a629f8abb96163db:
      image_group_id: I1KG5487
      title: ''
      volume_number: 1
      total_pages: 250
      base_file: v001.txt
