id: ID5ABD8BC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:22:51+00:00'
last_modified: '2022-06-08T16:23:28.401796+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5479
  title: མངོན་རྟོགས་རྒྱན་འགྲེལ་དང་དབུ་མའི་རྟེན་འབྲེལ་སྟོད་པ་སོགས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    995A:
      image_group_id: I1KG5487
      title: ''
      total_pages: 250
      order: 1
      base_file: 995A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
